### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ariaghora** [ariaghora/noe#1]
# Near-future plans
- [ ] Examples for multi-layer perceptron (low-level usage)
- [ ] Complete broadcasting for all operations
- [ ] Proper documentation
- [ ] Wrapper classes for some classification algorithms
- [ ] Operator overloading

# Long-term plans
- [ ] Use faster backend such as OpenCL or BLAS
- [ ] Implement autograd
